### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by drewbo** [kapadia/usgs#23]
Trying to use the command line tool to search and getting connection errors each time:

```
    usgs search LANDSAT_8 --node EE --start-date 20150401 --end-date 20150501

    Traceback (most recent call last):
  File "/usr/local/bin/usgs", line 9, in <module>
    load_entry_point('usgs==0.1.5', 'console_scripts', 'usgs')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/usgs/scripts/cli.py", line 166, in search
    data = api.search(dataset, node, lat=latitude, lng=longitude, distance=distance, ll=lower_left, ur=upper_right, start_date=start_date, end_date=end_date, where=where, extended=extended, api_key=api_key)
  File "/usr/local/lib/python2.7/site-packages/usgs/api.py", line 266, in search
    r = requests.post(USGS_API, xml)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

Ran `pip install usgs --upgrade` right beforehand so should have the most recent deps, OSX 10.9.2

**Comment by kapadia** [comment]
@drewbo Thanks for flagging this. USGS has 2 apis: soap and json. The json api is newer, but it was released after this client was built. Checking logs from the Landsat to AWS ingestion, there's a slow degradation against the soap endpoint.

Submitting a request to the json api:

```
https://earthexplorer.usgs.gov/inventory/json/search?jsonRequest={"datasetName":"LANDSAT_8","startDate":"2015-04-01","endDate":"2015-05-01","maxResults":"10000","startingNumber":"1","sortOrder":"ASC","node":"EE"}
```

is relatively quick. My guess is that USGS is ramping down support/maintenance for the other api. Unfortunately I can only speculate. Looks like it's time for this client to receive a refactor to leverage the json api.

**Comment by drewbo** [comment]
Is the JSON API documented anywhere? I noticed, for instance, that the `endDate` parameter has no effect on the returned results. I'm also worried I either broke it or am blocked because it stopped returning results to me after a while (and I put in some crazy input parameters to test things out)

Update: it's showing results again! Not sure what happened there.

**Comment by kapadia** [comment]
> Is the JSON API documented anywhere?

Yes, but it's behind an authenticated page, available to those with sufficient EROS privileges ...

> I noticed, for instance, that the endDate parameter has no effect on the returned results.

Hrm. By default, if `endDate` is left off, their servers default to the current date. Perhaps this is a timeout. Can you try:

```
usgs search --node EE LANDSAT_8 --start-date 2015-07-07 --geojson | jq ""
```

**Comment by kapadia** [comment]
> I'm also worried I either broke it or am blocked because it stopped returning results to me after a while (and I put in some crazy input parameters to test things out)

You could check by requesting from another IP. Try spinning up an EC2.

**Comment by drewbo** [comment]
This returns fine:

```
usgs search --node EE LANDSAT_8 --start-date 2015-07-07 --geojson | jq ""
```

**Comment by kapadia** [comment]
Cool. Something is up on the USGS end, especially if the query does not respect `endDate`. How about this one:

```
usgs search --node EE MODIS_MYD09A1 --start-date 2015-01-01 --end-date 2015-05-05
```

It has a wider date range than your L8 query, but hits a MODIS dataset. FYI, your Landsat query above also timed out for me, but these two examples are working. If this works for you, I suspect there's some activity happening with the L8 dataset.

**Comment by drewbo** [comment]
MODIS was good as well

**Comment by kapadia** [comment]
Interesting. I think there's something going on with the `LANDSAT_8` dataset. Part of it has to do with not respecting the `endData` param. Likely factor is that querying over such a large date range returns a lot of scenes. The `maxEntries` param is not exposed via the CLI, but you can try:

``` python
from usgs import api
api.search('LANDSAT_8', 'EE', start_date='2015-04-01', end_date='2015-05-01', max_results=10)
```

This request returned pretty quick for me.

**Comment by kapadia** [comment]
@drewbo Just sent an email to (I think) the folks maintaining this service. Will follow up when I hear back.

> > Hi,
> > 
> > We've been using the USGS Inventory Service. Recently we've noticed changes in the response returned from queries specific to the Landsat 8 dataset.
> > 
> > I've noticed that the `startDate` and `endDate` are not being respected. For example, a query for scenes between 2015-04-01 and 2015-04-02 actually returns the most recently acquired scenes.
> > 
> > Here is an example demonstrating the unexpected behavior.
> > 
> > https://gist.github.com/kapadia/f103feb22078129cb076

**Comment by drewbo** [comment]
Awesome. Thanks again for the help with this. I'll likely come back to it early next week.

**Comment by kapadia** [comment]
No word yet 😒, and the problem seems to persist.

**Comment by kapadia** [comment]
@drewbo see the response from EROS below. In addition to the changes they made, it looks like we have a lesson learned. Spread large date ranges over multiple requests to limit each response.

> Thank you for contacting the USGS Earth Resources Observation and Science (EROS) Center.
> Our apologies for the delay in responding to your email.  We appreciate your patience.
> Just a follow-up to see if your issues have been resolved?
