### ISSUE TITLE
USGSError: SEARCH_ERROR

### ISSUE THREAD

**Issue by zotix** [kapadia/usgs#26]
Cannot search without API

![2015-10-06_133207](https://cloud.githubusercontent.com/assets/1305553/10301665/b6a5304c-6c2e-11e5-8ea9-f7088fe02ea2.png)

**Comment by semiautomaticgit** [comment]
Hello,
is this issue solved or the API Key is required for searching?
Thank you

**Comment by AmitAronovitch** [comment]
You need to call api.login (it saves the key in `~/.usgs`, where the other api functions expect to find it)
I guess the documentation and/or the error message should be fixed.
Maybe should ping the OP to check if answered by now...

**Comment by fitoprincipe** [comment]
Than you @AmitAronovitch ! That is it
