### ISSUE TITLE
Mark as unmaintained

### ISSUE THREAD

**Issue by sgillies** [kapadia/usgs#30]
Correct me if I'm wrong @kapadia @scisco.

**Comment by kapadia** [comment]
@sgillies Perhaps this library hasn't seen much attention, but it's actively used, especially for Landsat on AWS.

**Comment by scisco** [comment]
Agreed. We use this library in at least two projects.

**Comment by sgillies** [comment]
@scisco @kapadia how about we move it to either the planet or developmentseed orgs? As things stand, issues and PRs are coming to Mapbox and we're not users of this package.

**Comment by kapadia** [comment]
@sgillies let's move it to the planet org. i no longer have admin privileges on this repo, do you have scope to transfer it?

**Comment by sgillies** [comment]
@kapadia It looks like I'll need to transfer it to your personal account and let you take it from there.

**Comment by kapadia** [comment]
That's fine. Thanks for looking in to it. Hope you're doing well, @sgillies!
