### ISSUE TITLE
Demise of the USGS/EROS SOAP API

### ISSUE THREAD

**Issue by ghost** [kapadia/usgs#32]
I just received the message copied below. Is there any plan to support the new API or will this library stop working after May 15?

> Dear Machine-To-Machine EarthExplorer User.
> 
> USGS/EROS will retire support for the SOAP API on May 1, 2017.
> 
> The JSON / REST API is the primary Machine-To-Machine protocol and after May 1st it will be the only API supported for bulk data downloads.
> 
> https://earthexplorer.usgs.gov/inventory/documentation
> 
> A two week grace period will be in effect to provide more time if you need it to make the transition from SOAP to JSON.  
> 
> 
> However, all SOAP calls made after May 15 will be bounced and only JSON calls will be honored for data downloads.
> 
> 
> Thank you for your cooperation in this matter,
> 
> 
> Tim Smith
> Data Management & Information Task Lead
> Stinger Ghaffarian Technologies (SGT, Inc.)
> Contractor to the U.S. Geological Survey (USGS) 
> Earth Resources Observation and Science (EROS) Center
> 47914 252nd Street
> Sioux Falls, SD  57198
>

**Comment by kapadia** [comment]
Hi @citterio - thanks for the note. Work has started to support the JSON api over at https://github.com/kapadia/usgs/tree/json-api. This will be reach parity with the SOAP implementation before USGS fully deprecates the SOAP API.

**Comment by ghost** [comment]
Awesome!

**Comment by kapadia** [comment]
The library has been updated to access USGS's JSON API. The SOAP implementation entirely deprecated. Please note that all responses will have a slightly different data structure since we're no longer coercing XML into JSON, but rather preserving the response from USGS.
