### ISSUE TITLE
USGSError: DATASET_NOT_CONFIGURED

### ISSUE THREAD

**Issue by tzoiker** [kapadia/usgs#34]
I am trying to run an example from the README, but keep getting the following error: `USGSError: DATASET_NOT_CONFIGURED: Dataset is not configured for Inventory Service`.
Python 2.7.12, usgs 0.2.0.

**Comment by tzoiker** [comment]
It fails for LANDSAT_8 dataset. However, search, e.g. `api.search('LANDSAT_ETM_SLC_OFF', 'EE', lat=50, lng=30, start_date='2006-01-01', end_date='2006-01-02')` fails for LANDSAT_TM and LANDSAT_ETM_SLC_OFF as well.

**Comment by kapadia** [comment]
@tzoiker This appears to be due to USGS's transition to a collection based archive (https://landsat.usgs.gov/landsat-collections). Instead of using the `LANDSAT_8` dataset, try the new collection dataset, `LANDSAT_8_C1`.
