### ISSUE TITLE
Machine to Machine Privileges

### ISSUE THREAD

**Issue by Msawtelle** [kapadia/usgs#37]
Can you possibly explain how to get machine to machine privileges on my EROS account? I successfully used the api.search() method to find some scene ids, but when I try and download the scenes the following error is raised.

raise USGSError('%s: %s' % (error_code, error))
usgs.USGSError: AUTH_UNAUTHORIZED: Forbidden - Approved role required for access to 'download' method.

**Comment by kapadia** [comment]
Hi @Msawtelle - you'll have to contact EROS directly. On their [registration page](https://ers.cr.usgs.gov/register/) they have an email that you may use to contact their customer support.

**Comment by Msawtelle** [comment]
Thanks for the help!
