### ISSUE TITLE
datasets codes

### ISSUE THREAD

**Issue by fitoprincipe** [kapadia/usgs#43]
Hello, I'd like to know where do I find the dataset's codes? I have searched everywhere and can't find it. `LANDSAT_8_C1` works fine, but what are the codes of the other datasets??

Thank you

**Comment by kapadia** [comment]
@fitoprincipe using the CLI you can run the following to see all datasets on the EarthExplorer node:

```
usgs datasets EE
```

**Comment by fitoprincipe** [comment]
great! I'll try it. Thank you @kapadia. I'll close the issue as soon as I get the results.
