### ISSUE TITLE
Possible Update?

### ISSUE THREAD

**Issue by yurikoif** [kapadia/usgs#50]
I recently experience being unable to search for and download imageries through this API.
According to [https://lta.cr.usgs.gov/EEHelp/ChangestoBulk](url), it seems that something needs to be done to adapt.
Is there a plan for the update? Thanks!

**Comment by kapadia** [comment]
There's been some downtime lately. I'm aware of the need to migrate to their v1.5 API. I'm waiting for documentation to be released before making modifications.

**Comment by yurikoif** [comment]
> I recently experience being unable to search for and download imageries through this API.
> According to [https://lta.cr.usgs.gov/EEHelp/ChangestoBulk](url), it seems that something needs to be done to adapt
> Is there a plan for the update? Thanks!
