### ISSUE TITLE
USGS error

### ISSUE THREAD

**Issue by abhiramp1** [kapadia/usgs#59]
Can I resolve this from my end. I did try to update my login username and password but the issue persists 

usgs.USGSError: {"errorCode":"AUTH_EXPIRED","errorMessage":"API key has expired due to inactivity","data":null,"requestId":0,"sessionId":null,"version":null}

**Comment by kapadia** [comment]
@abhiramp1 you might check for the `.usgs` file in your home directory. If that exists, remove it, and log in again.

**Comment by abhiramp1** [comment]
Thank you
