### ISSUE TITLE
New endpoint for `dataset-download-options`

### ISSUE THREAD

**Issue by aazuspan** [kapadia/usgs#64]
Hi @kapadia, I have a use case where I need to be able to identify dataset download options (products) without knowing entity IDs. This isn't possible with the `download-options` endpoint used by `api.download_options` because it returns nothing if the entity ID list is empty, so `usgs` would need a new function and payload `dataset_download_options` that uses the `dataset-download-options` endpoint.

I'm happy to add those functions and make a PR if you think it's worth including in `usgs`. Let me know what you think!

**Comment by kapadia** [comment]
@aazuspan - happy to take further contributions from you :) I believe that end point used to be implemented in an old version. Changes to the USGS API necessitated a re-write of this library, and that end point was left off in the process.

**Comment by aazuspan** [comment]
Great, I'll make a PR!
